Update raster episodes
carpentries-incubator/r-geospatial-urban pull request #43
Opened 2024-05-01 10:58 UTC by cforgaci

Updates include:

- Reviewed phrasing: disambiguation, consistency, elaboration, reducing repetition
- Replaced superseded `coord_quickmap()` with `coord_equal()`
- Fixed links
- Reduced histogram section

2024-05-20 15:07 UTC, iurriayanez reviewed
Looks good! I did just two tiny suggestions to improve clarity in the naming of a code block and in the writing. 
(First time doing a review, I hope I managed to do it right!)

2024-05-20 15:07 UTC, iurriayanez commented on episodes/17-work-with-multi-band-rasters.Rmd
> +- Identify what bands we want to render in the red, green and blue regions. The `plotRGB()` function defaults to a 1=red, 2=green, and 3=blue band order. However, you can define what bands you would
```suggestion
- Identify what bands we want to render in the red, green and blue regions. The `plotRGB()` function defaults to a 1=red, 2=green, and 3=blue band order. However, you can define what bands you would like to plot manually. Manual definition of bands is useful if you have, for example, a near-infrared band and want to create a colour infrared image.
```

2024-05-20 16:08 UTC, cforgaci commented
> Looks good! I did just two tiny suggestions to improve clarity in the naming of a code block and in the writing. (First time doing a review, I hope I managed to do it right!)

@iurriayanez, perfect. You even suggested changes, which is impressive for a first review 👍 I committed both changes.

2024-05-21 06:37 UTC, cforgaci commented on episodes/13-intro-to-raster-data.Rmd
> +This lesson uses the `terra` package in particular. If you have not installed it yet, do so by running `install.packages("terra")` before attaching it with `library(terra)`.
```suggestion
This lesson uses the `terra` package in particular. If you have not installed it yet, do so by running `install.packages("terra")` before loading it with `library(terra)`.
```

2024-05-21 06:39 UTC, cforgaci commented on episodes/14-plot-raster-data.Rmd
> +This lesson uses the `terra` package in particular. If you have not installed it yet, do so by running `install.packages("terra")` before attaching it with `library(terra)`.
```suggestion
This lesson uses the `terra` package in particular. If you have not installed it yet, do so by running `install.packages("terra")` before loading it with `library(terra)`.
```

2025-01-30 19:52 UTC, cforgaci commented
@dcannatella this PR has been pending for quite some time and I think most issues are already solved. I will be processing and merging it at the end of the day tomorrow 31 January. If you want and have time to suggest any additional changes, please do so before that here. Feel free to make code suggestions or simly leave comments.

2025-01-31 10:29 UTC, dcannatella approved these changes

2025-01-31 11:52 UTC, dcannatella requested changes
Episodes 13-17 reviewed

2025-01-31 11:52 UTC, dcannatella commented on episodes/15-reproject-raster-data.Rmd
> +For this episode, we will be working with Digital Terrain Model data. This differs from the surface model data we have been working with so far in that the digital surface model (DSM) includes the to
For this episode, we will be working with Digital Terrain Model data. This differs from the surface model data we have been working with so far in that the digital surface model (DSM) includes the tops of trees and buildings, while the digital terrain model (DTM) shows the ground level.

![Comparison between Digital Surface Model (DSM) and Digital Terrain Model (DTM)](https://raw.githubusercontent.com/NEONScience/NEON-Data-Skills/dev-aten/graphics/lidar-derived-products/DSM-DTM.png)
Comparison between Digital Surface Model (DSM) and Digital Terrain Model (DTM). The DSM includes elevations of natural and man-made features such as trees and buildings, while the DTM represents the bare ground surface. *Image Source: [NEON Science](https://www.neonscience.org/resources/learning-hub/tutorials/chm-dsm-dtm)*

2025-01-31 11:52 UTC, dcannatella commented on episodes/15-reproject-raster-data.Rmd
> +For this episode, we will be working with Digital Terrain Model data. This differs from the surface model data we have been working with so far in that the digital surface model (DSM) includes the to
Suggestion: The image provides a clear comparison between the DSM and DTM, making the distinction between the two much easier to understand. It would be helpful to keep it here for clarity. What do you think?

2025-01-31 11:52 UTC, dcannatella commented on episodes/15-reproject-raster-data.Rmd
> +If we look at the axes, we can see that the units, and therefore the projections, of the two rasters are different. When this is the case, `ggplot2` will not render the image. It will not even throw
If we examine the axes, we can see that the units (and thus the projections) of the two rasters differ. In such cases, ggplot2 will still render the images, but they may not be visible because they are positioned far outside the plot's viewable area. The function doesn't throw an error, but rather completes the rendering process, which can make it seem like nothing is wrong. To better understand this, we can compare the Coordinate Reference Systems (CRSs) of the DTM and hillshade data to see how they differ.

2025-01-31 11:52 UTC, dcannatella commented on episodes/15-reproject-raster-data.Rmd
> +# Challenge: check the CRS
# Challenge: compare the CRSs

2025-01-31 11:52 UTC, dcannatella commented on episodes/15-reproject-raster-data.Rmd
> +Because the two rasters are in different CRS, they do not line up when plotted in R. We need to reproject (or change the projection of) `DTM_hill_TUD` into the Amersfoort / RD New CRS.
Because the two rasters are in different CRSs, they do not line up when plotted in R. We need to reproject (or change the projection of) DTM_hill_TUD into the Amersfoort / RD New CRS (EPSG: 28992).

2025-01-31 11:52 UTC, dcannatella commented on episodes/15-reproject-raster-data.Rmd
> +These two resolutions are different, but they represent the same data. We can tell R to force our newly reprojected raster to be the same as `DTM_TUD` by adding a line of code `res = res(DTM_TUD)` wi
Although these two rasters have different resolutions, they represent the same data. We can tell R to force our newly reprojected raster to be the same as `DTM_TUD` by adding a line of code `res = res(DTM_TUD)` within the `project()` function.

2025-01-31 11:52 UTC, dcannatella commented on episodes/16-raster-calculations.Rmd
> +Let's say we are interested in mapping the heights of trees and buildings across an entire urban area. To that end, we can calculate the difference between the Digital Surface Model (DSM, tops of tre
Let's say we are interested in mapping the heights of trees and buildings across an urban area. To that end, we can calculate the difference between the Digital Surface Model (DSM, tops of trees and buildings) and the Digital Terrain Model (DTM, ground level). The resulting dataset is referred to as a Canopy Height Model (CHM) and represents the actual height of trees, buildings, etc. with the influence of ground elevation removed.

2025-01-31 11:52 UTC, dcannatella commented on episodes/16-raster-calculations.Rmd
>  ![Source: National Ecological Observatory Network (NEON).](https://datacarpentry.org/r-raster-vector-geospatial/fig/dc-spatial-raster/lidarTree-height.png)
<img src="https://datacarpentry.org/r-raster-vector-geospatial/fig/dc-spatial-raster/lidarTree-height.png" alt="Source: National Ecological Observatory Network (NEON)." width="75%" />

2025-01-31 11:52 UTC, dcannatella commented on episodes/16-raster-calculations.Rmd
> +Now that we have created a new raster, let’s export the data as a GeoTIFF file using the `writeRaster()` function.
Now that we have created a new raster, let’s export the data as a GeoTIFF file using the `writeRaster()` function.
A GeoTIFF is a metadata standard that has the georeferencing information embedded within the image.

2025-01-31 11:52 UTC, dcannatella commented on episodes/17-work-with-multi-band-rasters.Rmd
> -## Import a Specific Band
Suggestion: I’m fine with cutting this part. Could this be turned into a quick challenge instead? For example, something like "Plot the green or blue bands" might be a good option.

2025-01-31 11:52 UTC, dcannatella commented on episodes/17-work-with-multi-band-rasters.Rmd
> +```{r plot-rgb-band1-hist}
Suggestion: Perhaps we could drop this section as well. While it’s useful for reinforcing concepts, it doesn’t seem strictly necessary for the next step.

2025-01-31 22:15 UTC, cforgaci commented on episodes/13-intro-to-raster-data.Rmd
> -This map shows our Digital Surface Model, that is, the elevation of our study site including buildings and vegetation. From the legend we can confirm that the maximum elevation is around 90, but we c
It is not deleted, but moved to line 139.

2025-01-31 22:37 UTC, cforgaci commented on episodes/15-reproject-raster-data.Rmd
> +For this episode, we will be working with Digital Terrain Model data. This differs from the surface model data we have been working with so far in that the digital surface model (DSM) includes the to
@dcannatella, I added the figure, as suggested. Thanks!

2025-01-31 22:56 UTC, cforgaci commented on episodes/17-work-with-multi-band-rasters.Rmd
> -## Import a Specific Band
Good idea @dcannatella. I added it as a challenge.

2025-01-31 22:56 UTC, cforgaci commented on episodes/17-work-with-multi-band-rasters.Rmd
> +```{r plot-rgb-band1-hist}
Okay!

2025-01-31 23:56 UTC, merged