Revision session 1.1 and 1.2
carpentries-incubator/r-geospatial-urban pull request #47
Opened 2024-05-07 09:53 UTC by KyriJanssen

Added slides part 1.1
Revisions rmd files session 1.1 and 1.2

2024-05-16 10:47 UTC, cforgaci reviewed
Thanks @KyriJanssen! I left some comments.

2025-01-30 19:19 UTC, cforgaci commented
@alwil and/or @javisanmillan, can you please have a look at this PR? I will process and merge these at the end of the day on 31 January.

2025-01-31 07:21 UTC, javisanmillan requested changes

2025-01-31 07:21 UTC, javisanmillan commented on episodes/01-intro-to-r.Rmd
Given that we are at the very start of the workshop, should not we include a basic initial question that is "What is R and what is RStudio?"?

":::::::::::::::::::::::::::::::::::::: questions 
- What is R and what is RStudio?
- How can I find my way around RStudio?
- How can I manage projects in R?
- How can I install packages?
- How can I interact with R?
::::::::::::::::::::::::::::::::::::::::::::::::"

2025-01-31 11:50 UTC, alwil reviewed
Hi @cforgaci , I've added a few comments - feel free to adapt or disregard. I agree with all your comments. Also, some of the changes seem to be made to fit the workshop setting, but I think this should be also a more general resource, used also for self-learning.

2025-01-31 11:50 UTC, alwil commented on episodes/01-intro-to-r.Rmd
If that's the complete carpentry lesson, I would keep it. I understand it's not essential for the workshop with limited time, but for self-learning might be useful.

2025-01-31 11:50 UTC, alwil commented on episodes/01-intro-to-r.Rmd
> +The data we just downloaded is data about country statistics, containing information on, for instance, GDP and life-expectancy. We will work with this data later this morning
I agree. 'later in the lesson' or 'in the following episodes' might work better? instructors can adapt wording for specific workshop.

2025-01-31 11:50 UTC, alwil commented on episodes/02-data-structures.Rmd
> +# vector of words - or strings of characters- character data type. Note that we need to use '' to tell R that we are working with strings. If there is a ' mark in the string itselfs, such as s'Graven
```suggestion
# vector of words - or strings of characters- character data type. Note that we need to use quotation marks '' to tell R that we are working with strings. If there is a ' mark in the string itself, such as s'Gravenhage, then we use "".
```

2025-01-31 11:50 UTC, alwil commented on episodes/02-data-structures.Rmd
> +# vector of words - or strings of characters- character data type. Note that we need to use '' to tell R that we are working with strings. If there is a ' mark in the string itselfs, such as s'Graven
It's a matter of convention I guess, but in DCHSS, we teach it's a good practice to consistently use double quotation marks, as single ones are more often found in strings.  Either way, might be good to move this information to callout?

2025-01-31 11:50 UTC, alwil commented on episodes/02-data-structures.Rmd
> +character_vector <- c('Amsterdam', "'s Gravenhage", 'Delft')
well, again matter of convention, but personally, I would prefer to see all strings with double quotation marks

2025-01-31 11:50 UTC, alwil commented on episodes/02-data-structures.Rmd
> +str(combined_vector)
```suggestion
combined_vector
str(combined_vector)
```

2025-01-31 11:50 UTC, alwil commented on episodes/02-data-structures.Rmd
> +str(combined_vector)
For consistency with previous examples, I would print out vector before showing its structure

2025-01-31 11:50 UTC, alwil commented on episodes/02-data-structures.Rmd
> +#if we want to identify the values that are not missing we write the following
```suggestion
# to identify the values that are not missing we write the following
```

2025-01-31 11:50 UTC, alwil commented on episodes/02-data-structures.Rmd
> +#and if we want to sum all the non-missing values we write
```suggestion
#and to sum all the non-missing values we write
```

2025-01-31 11:50 UTC, alwil commented on episodes/02-data-structures.Rmd
> -::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
in the present form, two callouts were merged to one.  I would probably keep them separate as one refers to reordering, other the vector values. 

If we want to keep 2 callouts, this line needs to be reincluded

2025-01-31 11:50 UTC, alwil commented on episodes/02-data-structures.Rmd
> -:::::::::::::::::::::::::::::::::::::::::::::::::::: callout
to keep two callouts, this line needs to be reincluded

2025-02-01 09:39 UTC, cforgaci requested changes
@alwil thanks for the review! I processed the suggestions and left some comments.

Optionally, you can update your slides in this PR.

@alwil @KyriJanssen @javisanmillan I will merge this as soon as the current comments and suggestions are processed.

2025-02-01 09:39 UTC, cforgaci commented on episodes/01-intro-to-r.Rmd
@KyriJanssen, can you add this question please? The changes are made from your fork, so I cannot suggest changes directly.

2025-02-01 09:39 UTC, cforgaci commented on episodes/02-data-structures.Rmd
>  ### Note of caution
```suggestion
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

:::::::::::::::::::::::::::::::::::::::::::::::::::: callout

### Note of caution 
```

2025-02-01 09:39 UTC, cforgaci commented on episodes/02-data-structures.Rmd
> -:::::::::::::::::::::::::::::::::::::::::::::::::::: callout
@alwil see my suggestion below to split the callouts into two

2025-02-01 09:39 UTC, cforgaci commented on instructors/1-Intro-to-R-slides.qmd
@alwil @javisanmillan do you want to update the slides as well?

2025-02-02 20:19 UTC, cforgaci commented on episodes/01-intro-to-r.Rmd
Issue to be solved in https://github.com/carpentries-incubator/r-geospatial-urban/issues/68

2025-02-02 20:20 UTC, cforgaci commented on episodes/01-intro-to-r.Rmd
Issue to be solved in https://github.com/carpentries-incubator/r-geospatial-urban/issues/69

2025-02-02 20:23 UTC, cforgaci commented on episodes/02-data-structures.Rmd
> +# vector of words - or strings of characters- character data type. Note that we need to use '' to tell R that we are working with strings. If there is a ' mark in the string itselfs, such as s'Graven
Issue to be solved in https://github.com/carpentries-incubator/r-geospatial-urban/issues/70

2025-02-02 20:24 UTC, cforgaci commented on episodes/02-data-structures.Rmd
> +character_vector <- c('Amsterdam', "'s Gravenhage", 'Delft')
To be addressed as part of #70

2025-02-02 20:24 UTC, cforgaci commented on episodes/02-data-structures.Rmd
> +character_vector <- c('Amsterdam', "'s Gravenhage", 'Delft')
Dropping this suggestions to keep the issue clean for #70. To be solved there.

2025-02-02 20:27 UTC, cforgaci commented on episodes/02-data-structures.Rmd
> -::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
Issue to be solved in https://github.com/carpentries-incubator/r-geospatial-urban/issues/71

2025-02-02 20:28 UTC, cforgaci commented on episodes/02-data-structures.Rmd
> -:::::::::::::::::::::::::::::::::::::::::::::::::::: callout
To be solved as part of #71

2025-02-02 20:34 UTC, cforgaci commented
@KyriJanssen, @fcjerome @javisanmillan @alwil, thanks for this PR. There were a few small things that were not solved, but I moved them into issues and we can take care of those after the workshop. This is ready to be merged.

2025-02-02 20:34 UTC, merged